### ISSUE TITLE
Thoughts for gaining more engagements

### ISSUE THREAD

**Issue by just4fun** [IFS49F/poker#71]
@hyjk2000 @hiveer @LeoLeoLei 

Dear friends,

As you know, currently there are more and more teams using this poker tool in their scrum meetings, some of them have already used this tool for a long time.

According to our original plan, this tool will always be free but happy to see any donation. The reason to create this ticket here is not saying that there are less donation in last months, but I'd like to share more thoughts on what we could get from this project.

Based on the experience in my another free open source side project ([the React Native app](https://github.com/just4fun/stuhome)), I got following benefits.

- Real users (Poker 🎉)
- GitHub stars (Poker 🎉)
- Positive feedbacks (Poker 🤔)

For the last item, we really got less feedback from our users, one of the reasons is that we didn't provide a way for users to give their feedbacks, we only have an Octocat banner at the top right.

For the RN app I created, I nearly received feedback from users every month, since I gave users entrance to provide their feedback (in app settings, and also created some posts in different forums to provide feedback way).

<img width="300" alt="feedback" src="https://user-images.githubusercontent.com/7512625/57066030-b58db700-6cfd-11e9-90c9-d39b6d437925.png">

Do you think it will be useful if we give users a notification banner when they access a room? the behavior is similar like this package: https://fkhadra.github.io/react-toastify/ (we will create it by our own if you all agree with notification way).

<img width="334" alt="notification" src="https://user-images.githubusercontent.com/7512625/57066832-eec72680-6cff-11e9-9d49-5f46b670b846.png">

Open to discussion.

**Comment by LeoLeoLei** [comment]
I am really sorry for this late response since i have not check my gmail for a long time.

Actually, There is already a feedback entry to users such as issue of gitHub. 🤭I remember a locales issue. It has been resolved by James.

However, it is only for developers. We have BA,QA and PJM. They may not have an account and i think provide the feedbacks via gitHub is little complicated for them. So i agree with you. We are able to pick up several comments that are we interested in and improve our Pokers.

One question. How often are you inform the user about the notification? First enter the room? Will you provide a button to disable the notification?
E.g. 
<img width="300" alt="notification" src="https://user-images.githubusercontent.com/49667087/58919157-a916d700-875f-11e9-9268-e553db0c5211.png">

From my side. I hate to be notified every time when i enter the room.Therefore, Can we add an icon for the feedback or donation next to the gitHub icon ? I think we are able to always keep it.
E.g.
<img width="300" alt="feekback" src="https://user-images.githubusercontent.com/49667087/58919633-5fc78700-8761-11e9-8576-9f777b58835c.png">

Any thoughts?

**Comment by hyjk2000** [comment]
I totally agree with you that we could do something to improve our feedback channel. However, since our users would almost always will be software development teams, we can work out ways more suitable for them, perhaps better than just pop-ups asking for feedbacks.

First, GitHub issue is still a viable way for our user to report bugs and suggest new features. I suppose most, if not all, our users would have no problem finding our GitHub repo. In addition to that, we can create a [Gitter](https://gitter.im) channel if we are ready for some more real-time communication with the users.

As for notifications, they are better used to announce new features, which our users would much more interested. Simply store a timestamp in `LocalStorage` whenever the user has received the notification so we do not spam the user with the same content.
